/*
   This is little program to update the file version.h in the current
   directory.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int ac, char *av[]) {

   FILE *fp;
   int i,minor_version=0, major_version=0, compile_pass=0;
   int updt_miv=0;
   int updt_mav=0;
   int updt_cop=0;
   int updt_new=0;
   char buf[80];
   char *pc;

   if (ac<2 || ac>4) {
      fprintf(stderr,"\nusage: updversion -M -m -c -n\n\n");
      fprintf(stderr,"generates and updates the version.h file in the current directory\n\n");
      fprintf(stderr,"options: -M  increments major version number\n");
      fprintf(stderr,"         -m  increments minor version number\n");
      fprintf(stderr,"         -c  increments compile pass number\n");
      fprintf(stderr,"         -n  generates a new version.h file\n\n");
      exit(-1);
   }

   for (i=1; i<ac; i++) {
      if (strcmp(av[i],"-M")==0) updt_mav=1;
      if (strcmp(av[i],"-m")==0) updt_miv=1;
      if (strcmp(av[i],"-c")==0) updt_cop=1;
      if (strcmp(av[i],"-n")==0) updt_new=1;
   } 

   if (!updt_mav && !updt_miv && !updt_cop && !updt_new) {
      fprintf(stderr,"\none ore more unknown options. Abort!\n\n");
      exit(-1);
   }

   if (!updt_new) {
      fp=fopen("version.h", "rb");
      if (!fp) {
         fprintf(stderr,"can't find file version.h. Abort!");
         exit(-1);
      }
       
      fgets(buf, 80, fp);
      fgets(buf, 80, fp);   /* skip the first two lines */
      fgets(buf, 80, fp);
      pc=strtok(buf," ");
      pc=strtok(NULL," ");
      pc=strtok(NULL," ");
      major_version=atoi(pc);
      fgets(buf, 80, fp);
      pc=strtok(buf," ");
      pc=strtok(NULL," ");
      pc=strtok(NULL," ");
      minor_version=atoi(pc);
      fgets(buf, 80, fp);
      pc=strtok(buf," ");
      pc=strtok(NULL," ");
      pc=strtok(NULL," ");
      compile_pass=atoi(pc);

      fclose(fp);

      if (updt_mav) { major_version++; minor_version=0; compile_pass=0; }
      if (updt_miv) { minor_version++; compile_pass=0; }
      if (updt_cop) compile_pass++;
   }

   fp=fopen("version.h", "wb");
   if (!fp) {
      fprintf(stderr,"can't create file version.h. Abort!");
      exit(-1);
   }
   fprintf(fp,"/* generated by updversion. Don't edit! */\n\n");
   fprintf(fp,"#define MAJOR_VERSION %d\n", major_version);
   fprintf(fp,"#define MINOR_VERSION %d\n", minor_version);
   fprintf(fp,"#define COMPILE_PASS  %d\n", compile_pass); 
   fclose(fp);

   return 0;
}
